### ISSUE TITLE
关于raw_data目录下的data.zip解压失败问题

### ISSUE THREAD

**Issue by bliu187** [RidongHan/GHE-LPC#1]
您好！感谢您分享的工作。我在解压raw_data目录下的data.zip时，无论是在windows还是ubuntu系统下都没有成功，windows10下提示：“该文件为非压缩文件，无法打开”；ubuntu18.04提示：“unzip: cannot find zipfile directory in one of ./raw_data/data.zip”。

**Comment by RidongHan** [comment]
你好，
我猜测你可能是直接git clone的
这种做法，如果你本地的git 没有安装git lfs的话，clone下来的文件会是错误的，因为这里的所有.zip,.npy,.tar文件对于git来说都是大文件
建议安装 git lfs后再clone

祝好

**Comment by bliu187** [comment]
您好：

我按照您的建议，已经解压成功了，非常感谢！

祝好
